# Generated by Django 4.2.4 on 2023-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bitrh_date",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="uploads/profile_imgs/default_profile_img.jpg",
                upload_to="uploads/profile_imgs",
            ),
        ),
    ]
